apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 3000 # Grafana default port
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana

